defaults = {
    "unit": 1,
    "slice": 2, 
    "project": False,
    "do_integrate": True,
    "weight": 1., 
    "cond": 1., 
    "avg": True, 
    "do_log": True, 
    "slice_coord": 0,
    "max_pixels": None,
    "nlevels": 200,
    "cmap": "jet",
    "cbar_label": 'field',
    "cbar_tick_increment": None, 
    "plot_star": False,
    "plot_dm": False, 
    "isocontours": None, 
    "isocontour_field": None, 
    "color_isocontour": 'black', 
    "color_star": 'black',
    "color_dm": 'black', 
    "cbar_orientation": 'vertical', 
    "width": None,
    "title": None
}
